const cooks=[{id:1,name:"Mak Cik Siti",type:"Nasi Lemak · Malay Food",rating:4.9,reviews:128,time:"25–35 min",distance:"1.2 km",img:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=85",foods:[["Nasi Lemak Ayam",6,"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=85"],["Nasi Lemak Rendang",7,"https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=500&q=85"],["Mee Siam",5.5,"https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=500&q=85"],["Kuih Lapis",2.5,"https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=500&q=85"] ]},{id:2,name:"Ah Ma Kitchen",type:"Chinese · Home Cooked",rating:4.8,reviews:96,time:"30–40 min",distance:"1.5 km",img:"https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=200&q=85",foods:[["Home Chicken",7,"https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=500&q=85"]]},{id:3,name:"Dapur Kak Leha",type:"Malay · Mixing Food",rating:4.9,reviews:74,time:"25–35 min",distance:"1.7 km",img:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=85",foods:[["Ayam Penyet",6.5,"https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=500&q=85"]]},{id:4,name:"Uncle Man's Kitchen",type:"Asian Favorites",rating:4.7,reviews:58,time:"30–45 min",distance:"2.0 km",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=85",foods:[["Chicken Rice",6,"https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=500&q=85"]]}];
let current=cooks[0],cart=[];
const $=x=>document.getElementById(x);
function role(r){document.querySelectorAll('.role').forEach(x=>x.classList.remove('active'));$(r).classList.add('active');show(r==='customer'?'c-home':r==='cook'?'k-dashboard':'r-dashboard')}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}
function back(){show(current==='customer'?'c-home':currentRole==='cook'?'k-dashboard':'r-dashboard')}
function render(){popular.innerHTML=cooks.slice(0,2).map(c=>`<div class="food" onclick="openCook(${c.id})"><img src="${c.foods[0][2]}"><div><b>${c.name}</b><br>⭐ ${c.rating} · ${c.time}</div></div>`).join('');renderCooks();neworder.innerHTML=`<div class="lightcard"><b>Order #KB12345</b><p>Mak Cik Siti · 1.2 km</p><p>Nasi Lemak Ayam ×1 $6.00<br>Mee Siam ×1 $5.50</p><b>Total $14.00</b><br><button onclick="show('k-find')">Accept Order</button><button class="red">Decline</button></div>`}
function renderCooks(a=cooks){cooksEl=$('cooks');cooksEl.innerHTML=a.map(c=>`<div class="cook" onclick="openCook(${c.id})"><img src="${c.img}"><div><h3>${c.name} <small style="color:#4fa52f">● Online</small></h3><p>${c.type}</p><p>⭐ ${c.rating} (${c.reviews})</p><p>◷ ${c.time}　⌖ ${c.distance}</p></div></div>`).join('')}
function filter(q){renderCooks(cooks.filter(c=>(c.name+c.type).toLowerCase().includes(q.toLowerCase())))}
function openCook(id){current=cooks.find(c=>c.id===id);$('menu').innerHTML=`<div class="seller"><img src="${current.img}" style="width:55px;height:55px;border-radius:50%;object-fit:cover;float:left;margin-right:10px"><b>${current.name}</b><br>⭐ ${current.rating} · ${current.distance}<br><small>${current.type} · ◷ ${current.time}</small><div style="clear:both"></div></div><div class="lightcard" style="padding:0">${current.foods.map(f=>`<div class="dish"><img src="${f[2]}"><div><h3>${f[0]} <span style="float:right">$${f[1].toFixed(2)}</span></h3><p>Fragrant, freshly prepared home-style food made with care.</p></div><button class="plus" onclick="add('${f[0]}',${f[1]},'${f[2]}')">+</button></div>`).join('')}</div>`;show('c-menu')}
function add(name,price,img){cart.push({name,price,img});summary.innerHTML=cart.map(x=>`<div class="dish"><img src="${x.img}"><div><b>${x.name}</b><br>$${x.price.toFixed(2)}</div></div>`).join('')+`<div class="lightcard"><p>Subtotal <b style="float:right">$${cart.reduce((a,x)=>a+x.price,0).toFixed(2)}</b></p><p>Delivery Fee <b style="float:right">$2.50</b></p><hr><h3>Total <b style="float:right">$${(cart.reduce((a,x)=>a+x.price,0)+2.5).toFixed(2)}</b></h3><p>💳 PayNow / Bank Transfer<br><small>You will pay directly to the cook.</small></p><button onclick="place()">Place Order</button></div>`;show('c-summary')}
function place(){orderno.textContent='Order #KB'+Math.floor(10000+Math.random()*89999);seller.innerHTML=`<b>${current.name}</b><br><small>⭐ ${current.rating} · ${current.distance} · ${current.time}</small>`;cart=[];show('c-confirmed')}
function findRider(){setTimeout(()=>show('k-found'),600)}
render();